### ISSUE TITLE
[Bug]: Pam's Harvestcraft Trees and Crops aren't harvesting properly

### ISSUE THREAD

**Issue by SapixIV** [AllTheMods/ATM-10#974] opened 2024-10-29 15:29 UTC
### Possible Fixes

Yes

### Modpack Version

1.11

### What happened?

When attempting to harvest from trees it breaks the fruit off and it doesn't regrow. when harvesting from crops it completely removes them from the soil. As far as I understand, this is not intended behavior for Pam's Harvestcraft because it would render it impossible to grow any of their trees for the purpose of actually using their produce, as you put in 8 fruit and get only 8 fruit then it becomes an ordinary tree. IT also requires you to manually replant all Pam's crops when you try to harvest them.
Considering Pam's doesn't have this behavior in either by itself or in other mod-packs that use the same version of the mod, I'm inclined to think it is a conflict with a right-click-to-harvest mod of some sort. Apparently Pam's recently had an update to their tree mod that was supposed to fix the issues and work with right-click-to-harvest mods, so this problem may be at least partly fixed.

**Comment by Yogfan1** [comment] 2024-11-01 03:24
I am having the same result. This has made a good portion of the Pam's Harvestcraft annoying or less useful than intended. I hope that this gets fixed either in the pack or in the mod depending on if its a bad interaction or mod behavior itself.

**Comment by Crystal-Spider** [comment] 2024-11-12 00:00
Hi! I'm Harvest with ease author, the mod used to provide right-click-harvest functionality in ATM10.  
I heard about this bug only recently, but I found the cause and I'll release a new version with the fix soon!  
Thanks for the patience and sorry for the inconvenience!

**Comment by Crystal-Spider** [comment] 2024-11-12 17:05
HWE v9.3.0 has been released with the fix for this problem!

**Closed** 2024-11-22 11:19 UTC
Labels: Bug, Reported to Mod Dev, Mod Bug
