### ISSUE TITLE
[Bug + Feature]: NaN Health issue

### ISSUE THREAD

**Issue by xArkailzx** [AllTheMods/ATM-10#742] opened 2024-10-11 12:00 UTC
### **Modpack version: 0.62**

I'm playing on a dedicated server with a friend since a few days. When going to the stronghold, I used Ultimine to dig down faster and the "Ice breakers" ability from Relics to cancel my fall damage. However, when reaching the stronghold, We both fell down, and due to the ability of the ice breakers (and probably some random things I don't know), we both got to 0 hearts, screen shaking like crazy, unable to open inventory or get items. After some research, I identified this bug as a recurring "NaN Health" bug happening in 1.21. I had to use NBTExplorer to patch our playerdata and fix this, but my friend kept going to NaN Health at any damage taken. Finally, I ended up installing an additional mod, "NaNny" on the server to fix the issue completely.

**_I haven't seen anything related in the issues here, so even if my modpack version isn't the last one, that bug is probably not fixed yet._**

This bug is probably very specific and hard to reproduce, but there's still a chance someone else gets the same treatment.
This is a bug report but also a mod suggestion, since I'm suggesting to either add "NaNny" to the modpack, either fix the bug an other way.

I don't know what caused this bug, probably some f*cked up damage multiplier on the player from a curio, and I don't have any logs linked to it, which is why I'm suggesting the mod directly.

**PS: I'm using NaNny on the server since, and I have yet to find any issues with it.**

### NaNny: https://www.curseforge.com/minecraft/mc-mods/nanny

**Comment by TheBedrockMaster** [comment] 2024-12-20 08:25
Have you been able to recreate the issue on newer releases?

**Comment by xArkailzx** [comment] 2024-12-20 08:31
Not as for now, but feel free to try so. I tried to explain the steps as clearly as possible: Take fall damage repeatedly, then use the ice breakers at the last moment to cancel a big fall. However, I think the damage bug was coming from the aoe damage from the ice breakers. So without trying in multiplayer, I don't know.

**Comment by alekthefirst** [comment] 2024-12-25 17:31
Ultimately a duplicate of https://github.com/AllTheMods/ATM-10/issues/154

**Closed by alekthefirst** 2024-12-25 17:31 UTC
Labels: Bug, Duplicate, Suggestion
