### ISSUE TITLE
Mod addition : Adding Oritech in ATM 10

### ISSUE THREAD

**Issue by SouLBusterFr** [AllTheMods/ATM-10#1572] opened 2024-12-27 11:00 UTC
### Feature Details

Feel free to close if it makes a double with the cloused issue #957 that was closed because the mod was neither neoforge nor in curseforge as per the date of the issue.

However, things are different now : 
According to #2 and since it appears the mods supports neoforge and is in 1.21.1 l do feel like it's not innapropriate to rediscuss the topic of adding oritech in ATM 10 as it is in curseforge. since we currently (correct me if am wrong) don't have thermal in atm 10, I am positive that Oritech would have his place in the modpack and would bring some diversity compared to the trinity (Thermal, Mekanism, Industrial Foregoing) we mostly have in almost every ATM. Curious to have your thoughts on that.

**Comment by TheBedrockMaster** [comment] 2024-12-27 11:15
Use #2 for mod suggestions, Oritech is not being added due to having owo as a dependency library.

**Comment by TheBedrockMaster** [comment] 2024-12-27 11:15
Duplicate of https://github.com/AllTheMods/ATM-10/issues/957

**Closed by TheBedrockMaster** 2024-12-27 11:15 UTC
Labels: Duplicate, Suggestion, Invalid
