### ISSUE TITLE
[Crash]: Game crash related to Y

### ISSUE THREAD

**Issue by akklox3** [AllTheMods/ATM-10#632] opened 2024-09-29 12:00 UTC
### Possible Fixes

Yes

### Modpack Version

0.59

### What happened?

I had a lot of (3,400) stone in my backpack and when i pressed Y to find some more in other chests my game just crushes, every time
It's not happening when i try to do the same with just 1 stack(64) stone

### Crash Log

idk what should i write here

**Comment by alekthefirst** [comment] 2024-12-25 17:43
Resolved in ATM10 2.9 by removing the FindMe mod
Duplicate of https://github.com/AllTheMods/ATM-10/issues/543

**Closed by alekthefirst** 2024-12-25 17:43 UTC
Labels: Duplicate, Crash
