### ISSUE TITLE
[Crash]: The game crashed whilst initializing game Error: java.lang.IllegalStateException: Mod 'architectury' is not available!

### ISSUE THREAD

**Issue by OBS3SS1ON** [AllTheMods/ATM-10#839] opened 2024-10-20 17:20 UTC
### Possible Fixes

Yes

### Modpack Version

1.3

### What happened?

Hi i have architectury-13.0.6-neoforge on folder. but.
client load and get The game crashed whilst initializing game
Error: java.lang.IllegalStateException: Mod 'architectury' is not available!

### Crash Log

https://gist.github.com/OBS3SS1ON/c0b143721b5259a71f003694f8c2fb37

### Latest.Log

https://gist.github.com/OBS3SS1ON/7544e10970a5db7d256ac3ba23f982ef

**Comment by OBS3SS1ON** [comment] 2024-10-21 04:32
Thx fixed on version 1.4

**Comment by alekthefirst** [comment] 2024-12-22 15:13
Duplicate of https://github.com/AllTheMods/ATM-10/issues/130
Glad that it got fixed for you

**Closed by alekthefirst** 2024-12-22 15:13 UTC
Labels: Duplicate, Crash, Reported to Mod Dev
