### ISSUE TITLE
[Bug]: Synthetic ruber recipe still broken

### ISSUE THREAD

**Issue by frsfdc** [AllTheMods/ATM-10#1126] opened 2024-11-12 11:43 UTC
### Possible Fixes

Yes

### Modpack Version

1.18

### What happened?

I tried to autocraft synthetic rubber from modern industrialisation,it did yellow dye instead,even though I used sulfur

**Comment by Yamijiro** [comment] 2024-11-13 04:10
You can click the recepie in from JEI and lock the slots after that.

**Comment by KingSkel** [comment] 2024-11-15 00:34
Still broken, shouldn't have to dedicate a mixer solely for synthetic rubber. Yes, I could lock it. No, I don't want to.

**Comment by Yamijiro** [comment] 2024-11-15 03:47
> Still broken, shouldn't have to dedicate a mixer solely for synthetic rubber. Yes, I could lock it. No, I don't want to.

Modern Industrialization encourages the passive automation of resources through the overclock mechanic. The way the machines are intended to be used is to set a recepie, use upgrades and the overdrive module. They will get really fast processing speeds like this and will enable you to stock up products really fast.

**Comment by Minenot26** [comment] 2024-12-06 06:14
Sorry, that i have to say that. He is on the right way. 
The recipe is duplicated.
And even if you include it, the mixer doesn't work.
So the solution would be to remove the sulfur from the dye recipe.
![2024-12-06_06 17 05](https://github.com/user-attachments/assets/3fdb69dc-1408-4aee-aceb-521a52b7374a)
![2024-12-06_06 18 18](https://github.com/user-attachments/assets/b044690d-125e-46e6-88fd-63cf5c05bc36)
![2024-12-06_07 04 13](https://github.com/user-attachments/assets/27f19fde-975b-43e2-9efd-ff8a96fcc9c7)

**Comment by TheBedrockMaster** [comment] 2024-12-26 11:28
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1041

**Closed by TheBedrockMaster** 2024-12-26 11:28 UTC
Labels: Bug, Duplicate
