### ISSUE TITLE
[Crash]: Spontaneous crash and cannot reload world. Immediate crash.

### ISSUE THREAD

**Issue by Skaeren** [AllTheMods/ATM-10#346] opened 2024-08-26 05:36 UTC
### Possible Fixes

Yes

### Modpack Version

0.38

### What happened?

I was in a village close to spawn, about 30 minutes into a new world. I was building a house. I heard attack sounds, and went up to 2nd story to look outside and seen two villagers attacking each other. They were the villagers with kind of a priestly look and a golden halo above their head. They appeared to be casting spells at each other. 30 seconds after I first heard the sounds of combat the world crashed. I attempted to reload, and it spat me back out immediately with the same error of "Error: java.lang.IllegalStateException: Not building!

### Crash Log

https://gist.github.com/Skaeren/249215aa55642a5a8d45f04697277450

### Latest.Log

https://gist.github.com/Skaeren/205bfda78a35cd7e042586860e0df095

**Comment by alekthefirst** [comment] 2024-12-22 14:37
Duplicate of https://github.com/AllTheMods/ATM-10/issues/256
Fixed in Irons 3.4.5 released with ATM10 0.39

**Closed by alekthefirst** 2024-12-22 14:37 UTC
Labels: Duplicate, Crash, Reported to Mod Dev, Mod Bug
