### ISSUE TITLE
[Crash]: Tried to read NBT tag that was too big

### ISSUE THREAD

**Issue by SeanLatimer** [AllTheMods/ATM-10#765] opened 2024-10-13 17:09 UTC
### Possible Fixes

Yes

### Modpack Version

0.62

### What happened?

We've started seeing this crash when players join our server, [Packet Fixer](https://www.curseforge.com/minecraft/mc-mods/packet-fixer) which was also included in ATM 9 should fix this issue.

### Crash Log

https://gist.github.com/SeanLatimer/92f0d19f8d20c9fabdb9675e0191f2f0

**Comment by SeanLatimer** [comment] 2024-10-14 16:10
Quick update.

What we found causing it was having 20 filled 64K drives in an Extended ME Drive or any other inventory block. The crash seems to happen when looking at said block containing the drives and more sporadically when being in the same chunk.

We tested Packet Fixer which didn't seem to fix this problem for us.

**Comment by alekthefirst** [comment] 2024-12-24 13:12
Fixed in Jade 15.6.0 released with ATM10 0.66
Duplicate of https://github.com/AllTheMods/ATM-10/issues/393

**Closed by alekthefirst** 2024-12-24 13:12 UTC
Labels: Duplicate, Crash, Reported to Mod Dev, Mod Bug
