### ISSUE TITLE
[Quests issues]: Iron Jetpacks on ATM10

### ISSUE THREAD

**Issue by itskenny7** [AllTheMods/ATM-10#323] opened 2024-08-23 23:08 UTC
### Modpack Version

ATM10

### Describe the issue

Iron Jetpacks got added today but you can't craft it. Recipes don't work, please have a look.

**Comment by DaddyLongspoon** [comment] 2024-08-23 23:14
duplicate of [#310](https://github.com/AllTheMods/ATM-10/issues/310)

**Closed** 2024-09-28 02:16 UTC
Labels: Bug, Duplicate, Reported to Mod Dev, Mod Bug
