### ISSUE TITLE
[Bug]: Can't get the server started. 

### ISSUE THREAD

**Issue by yuriondelagrion** [AllTheMods/ATM-10#1554] opened 2024-12-26 18:41 UTC
### Possible Fixes

Yes

### Modpack Version

2.11

### What happened?

I am trying to install server files on my personal server, but it won't even start. I am attaching latest log, maybe someone can point me to the right fix, thank you.
[latest.log](https://github.com/user-attachments/files/18254791/latest.log)

**Comment by TheBedrockMaster** [comment] 2024-12-26 23:27
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1489

**Closed by TheBedrockMaster** 2024-12-26 23:27 UTC
Labels: Bug, Duplicate
