### ISSUE TITLE
[Bug]: Treats with genes are not working when right clicking bee

### ISSUE THREAD

**Issue by M4RC0Sx** [AllTheMods/ATM-10#245] opened 2024-08-12 08:45 UTC
### Possible Fixes

Yes

### Modpack Version

0.30

### What happened?

Right cliccking a bee with a treat with genes is no longer working, you need to use the incubator. It was working on 0.28

**Comment by Mithi83** [comment] 2024-08-12 13:29
Duplicate of #231

**Closed** 2024-10-05 13:07 UTC
Labels: Bug, Duplicate
