### ISSUE TITLE
[Bug]: Crash when typing "Eye" into occultism storage

### ISSUE THREAD

**Issue by SinnFullOne** [AllTheMods/ATM-10#1186] opened 2024-11-18 01:49 UTC
### Possible Fixes

Yes

### Modpack Version

atm 10 1.20

### What happened?

in the occolut storage typing eye into search ctds the game

**Comment by alekthefirst** [comment] 2024-12-22 15:58
Note to self: Likely findme keybind issue

**Comment by alekthefirst** [comment] 2024-12-23 13:28
Presumably resolved in ATM10 2.9 by removing the FindMe mod
Duplicate of https://github.com/AllTheMods/ATM-10/issues/543

**Closed by alekthefirst** 2024-12-23 13:28 UTC
Labels: Bug, Mod Bug
