### ISSUE TITLE
[Crash]: Dependency Conflict 

### ISSUE THREAD

**Issue by Ridge-Sanders** [AllTheMods/ATM-10#126] opened 2024-07-22 00:38 UTC
### Possible Fixes

Yes

### Modpack Version

10-0.16 (Latest)

### What happened?

Game fails to launch due to a conflict between two dependencies: **org.apache.logging.log4j.slf4j** and **org.apache.logging.slf4j** to **io.netty.buffer**. I've updated Java to the latest version (Java 22). I still have legacy versions of Java, including Java 21 and 8, though I am currently using the latest. No additional mods have been installed to the instance.

log4fixer is unresponsive. Doesn't do a thing to fix this problem.

If the Gist doesn't load please reach out to me.

### Crash Log

https://gist.github.com/Ridge-Sanders/8825d2decb1f2f9073ddd84ef898e168#file-gistfile1-txt

**Comment by alekthefirst** [comment] 2024-12-22 12:12
Duplicate of https://github.com/AllTheMods/ATM-10/issues/99

**Closed by alekthefirst** 2024-12-22 12:12 UTC
Labels: Duplicate, Crash
