### ISSUE TITLE
[Bug]: Master Infusion Crystal Dupe

### ISSUE THREAD

**Issue by AspireVibeez** [AllTheMods/ATM-10#820] opened 2024-10-19 01:06 UTC
### Possible Fixes

No

### Modpack Version

1.1

### What happened?

When crafting essence with Master Crystal in a crafting table on a stick, if you tab to do the same recipe it gives you more crystals depending on how many times you hit tab.

**Comment by alekthefirst** [comment] 2024-12-24 20:13
Duplicate of https://github.com/AllTheMods/ATM-10/issues/138

**Closed by alekthefirst** 2024-12-24 20:13 UTC
Labels: Bug, Duplicate
