### ISSUE TITLE
[Bug]: Client crash when searching @mystical in JEI and ME systems

### ISSUE THREAD

**Issue by AriaFyre** [AllTheMods/ATM-10#1118] opened 2024-11-11 13:36 UTC
### Possible Fixes

Yes

### Modpack Version

1.17a

### What happened?

when searching JEI and ME system for @mystical client crashes and have tested this on multiple accounts and different systems

**Comment by alekthefirst** [comment] 2024-12-22 21:11
I believe its quite likely findme mod triggering when pressing `y`, though i would like some logs to go with this

**Comment by alekthefirst** [comment] 2024-12-23 13:28
Presumably resolved in ATM10 2.9 by removing the FindMe mod
Duplicate of https://github.com/AllTheMods/ATM-10/issues/543

**Closed by alekthefirst** 2024-12-23 13:28 UTC
Labels: Bug, More Info, Mod Bug
