### ISSUE TITLE
[Crash]: Productive Bees 13.6.6 causes Client crash when a Sugar bee is spawned

### ISSUE THREAD

**Issue by ArcadeArchie** [AllTheMods/ATM-10#1504] opened 2024-12-22 11:27 UTC
### Possible Fixes

Yes

### Modpack Version

2.8

### What happened?

Currently if a sugar bee is spawned(naturally or not) is causes a player to crash the moment they see it.
this seems to be fixed in Productive Bees 13.6.7

### Crash Log

https://gist.github.com/ArcadeArchie/4020426ed49bca0ce9f0a0eb4eb7dbf6

### Latest.Log

https://gist.github.com/ArcadeArchie/84333bedb4ba4cdb66c4a6633f444d3c

**Comment by alekthefirst** [comment] 2024-12-22 11:30
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1493
Fixed in productive bees 1.21.1-13.6.7
Will be included in next ATM10 update

**Closed by alekthefirst** 2024-12-22 11:30 UTC
Labels: Duplicate, Crash
