### ISSUE TITLE
[Crash]: IE Garden cloche, Wither rose

### ISSUE THREAD

**Issue by Fangzwusky** [AllTheMods/ATM-10#887] opened 2024-10-24 12:07 UTC
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

Instant crash on joining game after trying too grow a wither rose in a Garden cloche.

Unable too continue game. Critical error, broken world.

Exit code: -1
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: The class blusunrize.immersiveengineering.client.utils.TransformingVertexBuilder does not implement interface VertexBufferWriter, which is required for compatibility with Sodium (see: https://github.com/CaffeineMC/sodium-fabric/issues/1620)

### Crash Log

https://gist.github.com/Fangzwusky/2d8cee32b013631d544b0de2c727c275

**Comment by Fangzwusky** [comment] 2024-10-24 22:11
Managed too solve the issues by moving player away with NTBEditor, then installing WorldEditor too replace the Garden Cloche with Sand.

Will stay away from IE until it's updated.

**Comment by psperneac** [comment] 2024-10-25 00:48
duplicate of #883

**Closed** 2024-10-25 06:14 UTC
Labels: Duplicate, Crash
