### ISSUE TITLE
[Bug]: Failing to join server after 2.11 update

### ISSUE THREAD

**Issue by B2TheMonkey** [AllTheMods/ATM-10#1559] opened 2024-12-26 21:43 UTC
### Possible Fixes

Yes

### Modpack Version

2.11

### What happened?

I updated our dedicated server to the newest version and when I try to join its giving me an error "io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:custom_payload'"
Looking through the error report it seems to be an issue with Irons Jewelry but not sure how to fix it.

### latest.log

https://gist.github.com/B2TheMonkey/944b8ff29f6e66113225270b83953a62

**Comment by TheBedrockMaster** [comment] 2024-12-26 21:45
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1540

**Closed by TheBedrockMaster** 2024-12-26 21:45 UTC
Labels: Bug, Duplicate
