### ISSUE TITLE
[Crash]: Attractor block from Restrictions causing crashes when using the /warp command

### ISSUE THREAD

**Issue by NikolaMC** [AllTheMods/ATM-10#1256] opened 2024-11-25 16:44 UTC
### Possible Fixes

Yes

### Modpack Version

1.24

### What happened?

Me and a couple of friends are playing on a server, and three of us started crashing when using the /warp command to teleport to each other's bases, all with the same crash report. I looked into the issue and found that the Attractor block from the Restrictions mod I placed in a mob farm seems to have been the cause. After removing it, the crashes completely disappeared for me.

https://mclo.gs/r95bb6q

### Crash Log

https://gist.github.com/NikolaMC/135d6d19e74b169dff9292ce9d156ea5

**Comment by alekthefirst** [comment] 2024-12-23 00:44
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1214
Fixed in restrictions 7.0.3, will be included in next ATM10 release

**Closed by alekthefirst** 2024-12-23 00:44 UTC
Labels: Duplicate, Crash, Reported to Mod Dev, Mod Bug
