### ISSUE TITLE
[Crash]: Journey map claiming chunks

### ISSUE THREAD

**Issue by RedStoneGamed** [AllTheMods/ATM-10#605] opened 2024-09-26 00:46 UTC
### Possible Fixes

Yes

### Modpack Version

0.57

### What happened?

i tried to claim chunks with journey map and the game crashed and now i cant open my world, there is also no backups. this is what the report said.

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "journeymap.api.v2.common.waypoint.WaypointGroup.isEnabled()" because the return value of "journeymap.common.waypoint.WaypointImpl.getGroup()" is null

plz help

### Crash Log

"C:\Users\damia\curseforge\minecraft\Instances\All the Mods 10 - ATM10\crash-reports\crash-2024-09-25_20.34.33-client.txt"

**Comment by alekthefirst** [comment] 2024-09-26 05:01
Journey Map dev is aware of the issue and has fixed it in a hither to unrealeased version of Journey Map. Expect the next JM update to include the fix

https://github.com/TeamJM/journeymap/issues/795

**Comment by mysticdrew** [comment] 2024-09-28 10:39
It is not really fixed. 
I need someone with the issue to stop ghosting me. If someone with the issue can come into discord, create a ticket in the support channel that is willing to run a couple test versions. Then I can fix it, I will not be releasing an update until that happens. I have been unable to reproduce it.

**Comment by Lobifu17** [comment] 2024-09-28 19:02
I have the same issue with crashlog and willing to help, just need to know which discord ATM or Journey Map? 
crashlog: https://mclo.gs/0cdmgF6
Issue: Loading into singleplayer world crashes after updating from 0.57 to 0.58 and journeymap upon load crashes the game

**Comment by mysticdrew** [comment] 2024-09-28 19:04
journeymap preferably

please create a ticket in the support channel. I will be able to help later this evening.

**Comment by RedStoneGamed** [comment] 2024-09-28 19:07
The problem isn’t with the crashing itself, it’s more of I claimed a chunk with Joni and it crashed my game . Tho. They updated atm 10 and now my world loads with journey map and Jmi but idk why it crashed when claiming

**Comment by mysticdrew** [comment] 2024-09-28 20:57
This error had something to do with minecolonies death points or another waypoint they are creating, not sure what yet. I likely won't get time to dig in more until Monday.

**Comment by McKitten** [comment] 2024-09-30 12:04
In my case I was running Xaeros but way point auto creation was turned off. I can't find what gravestone mod is in ATM 10. With my wither incident I actually would have blamed the gravestone mod but the latest.log saying otherwise.
Either way I feel it premature to be making this your problem without WTD looking at it first.

**Comment by mysticdrew** [comment] 2024-09-30 23:13
Journeymap 1.21-6.0.0-beta.26 has the fix, it is in the process of releasing

**Comment by JustAtlas** [comment] 2024-10-01 20:50
Good afternoon, I recently have the same issue with the modpack.
Modpack Version: ATM 10-0.60
MC Version: 1.21.1
Neoforge - 21.1.61

Journeymaps version: journeymap-neoforge-1.21-6.0.0-beta.26

Error at Launcher: The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "journeymap.api.v2.common.waypoint.WaypointGroup.isEnabled()" because the return value of "journeymap.common.waypoint.WaypointImpl.getGroup()" is null

**Comment by mysticdrew** [comment] 2024-10-01 20:55
I need your WaypointsData.dat file please.

**Comment by RedStoneGamed** [comment] 2024-10-01 20:57
Mine or justatlas’s?

**Comment by mysticdrew** [comment] 2024-10-01 20:57
Who ever's is still failing in beta.26

**Comment by RedStoneGamed** [comment] 2024-10-01 21:00
My claiming chunks with jmi works now lol

**Comment by JustAtlas** [comment] 2024-10-01 21:03
Sorry for my ignorance, how do I retrieve the .dat file?

**Comment by mysticdrew** [comment] 2024-10-01 21:06
> Sorry for my ignorance, how do I retrieve the .dat file?

in your minecraft install directory is a journeymap folder. 
So in there. 
`/journeymap/data/sp or mp/worldname/waypoints/` that file

**Comment by JustAtlas** [comment] 2024-10-01 21:08
[WaypointData.zip](https://github.com/user-attachments/files/17216525/WaypointData.zip)

**Comment by mysticdrew** [comment] 2024-10-02 11:15
@JustAtlas 
Can you come into the jm discord and into this thread please? 
https://discord.com/channels/239040424214396929/1289667150247890954

I have a test version to see if it resolves your issue.

**Comment by mysticdrew** [comment] 2024-10-04 17:47
This has been fully fixed in beta.27. 
Cause was addons were unintentionally queuing waypoints to render before journeymap was ready.

**Closed** 2024-10-26 08:19 UTC
Labels: Crash, Reported to Mod Dev, Mod Bug
