### ISSUE TITLE
[Bug]: Tangled hatred data model not forming

### ISSUE THREAD

**Issue by frsfdc** [AllTheMods/ATM-10#997] opened 2024-10-31 15:50 UTC
### Possible Fixes

Yes

### Modpack Version

1.14

### What happened?

I kept trying to right click the tentacle miniboss next to the lunar monstrosity,yet kept geeting tha message that there is no data model for it,even though there should be

**Comment by YocyCraft** [comment] 2024-11-01 06:07
Please right click the "root" part of tangled hatred. Other parts are another entity (`eternal_starlight:tangled_hatred_part`) which have weird interactions.

**Comment by YocyCraft** [comment] 2024-11-01 06:14
Maybe we can add `eternal_starlight:tangled_hatred_part` as a variant of tangled hatred. However now `variant` field of HNN data models doesn't work due to a bug.

**Comment by YocyCraft** [comment] 2024-11-01 06:46
https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/issues/70 Reported to HNN github repo.

**Comment by alekthefirst** [comment] 2024-12-22 23:56
Duplicate of https://github.com/AllTheMods/ATM-10/issues/832 and fix is also provided there

**Closed by alekthefirst** 2024-12-22 23:56 UTC
Labels: Duplicate
