### ISSUE TITLE
[Crash]: Sophisticated Storage Crash

### ISSUE THREAD

**Issue by panzeson** [AllTheMods/ATM-10#358] opened 2024-08-29 20:23 UTC
### Possible Fixes

Yes

### Modpack Version

0.41

### What happened?

I was trying to make the sophisticated storage controller and found that I couldn't shift click in the recipe (It always says the barrel is missing even though I have it in my inventory), so I began manually crafting the recipe in the sophisticated storage chest using the crafting upgrade and as soon as I put in some of the ingredients for the storage controller, the server crashed. Now, whenever I open the chest, the server keeps crashing since the items are still in the crafting grid.

### Crash Log

https://gist.github.com/panzeson/464a7c21ab711cad97c80058330696d5

### Latest.Log

https://gist.github.com/panzeson/197dbc465c2ebf0a7fce03f33450fcc7

**Comment by panzeson** [comment] 2024-08-29 20:29
It seems like it's whenever we craft the sophisticated storage controller anywhere, as soon as I put in the redstone comparator in the slot above the barrel in the crafting grid

**Comment by FernandoKayro** [comment] 2024-08-30 00:21
I'm having the same problem, here's my crash report: https://mclo.gs/rTA0Ou0

**Comment by alekthefirst** [comment] 2024-12-22 14:40
Duplicate of https://github.com/AllTheMods/ATM-10/issues/297
Fixed in Sophisticated Storage 0.10.27.827, released in ATM10 0.53

**Closed by alekthefirst** 2024-12-22 14:40 UTC
Labels: Duplicate, Crash, Reported to Mod Dev, Mod Bug
