### ISSUE TITLE
[Crash]: my game crashes and say 'architectury' is not available!'

### ISSUE THREAD

**Issue by SLYVERRR** [AllTheMods/ATM-10#488] opened 2024-09-13 00:14 UTC
### Possible Fixes

Yes

### Modpack Version

10-0.52

### What happened?

i opened the game once and it was working good i close the game reopen it it kept giving me this error

### Crash Log

https://gist.github.com/SLYVERRR/af87e7fc101bffae7b8b70035090a6ac

### Latest.Log

https://gist.github.com/SLYVERRR/57e7a65e2a6c63d231cfa63072fa7b40

**Comment by alekthefirst** [comment] 2024-12-22 15:08
Duplicate of https://github.com/AllTheMods/ATM-10/issues/130
Though given the age of the issue, unlikely to see a resolution

**Closed by alekthefirst** 2024-12-22 15:08 UTC
Labels: Duplicate, Crash, Reported to Mod Dev

**Comment by TheBedrockMaster** [comment] 2025-01-01 09:55
Duplicate of https://github.com/AllTheMods/ATM-10/issues/130

**Comment by TheBedrockMaster** [comment] 2025-01-01 09:56
See https://github.com/architectury/architectury-api/issues/528 and https://github.com/Draylar/omega-config/issues/26
