### ISSUE TITLE
[Bug]: Can't craft Potion of Ancient Knowledge

### ISSUE THREAD

**Issue by AIC1Drew** [AllTheMods/ATM-10#379] opened 2024-09-01 10:50 UTC
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

Can't craft Potion of Ancient Knowledge.  It currently doesn't allow you to put a Bottle o' Enchanting in a brewing stand (Multiplayer/Dedicated Server)

**Comment by juicedude** [comment] 2024-09-02 03:33
Currently on version 0.41 and can craft the potion in single player but could not in my group's multiplayer world. Attempting to put the Bottle o' Enchanting in brewing stand puts the item back in inventory.

**Comment by alekthefirst** [comment] 2024-12-22 18:29
Duplicate of https://github.com/AllTheMods/ATM-10/issues/117

**Closed by alekthefirst** 2024-12-22 18:29 UTC
Labels: Bug, Duplicate
