### ISSUE TITLE
[Crash]: Ticking block entity

### ISSUE THREAD

**Issue by dockillborn** [AllTheMods/ATM-10#1446] opened 2024-12-17 01:05 UTC
### Possible Fixes

Yes

### Modpack Version

2.5

### What happened?

I got a message from my friend that the server crashed while I was at work, I'm sorry I can't give a better explanation to what the cause here is. 

### Crash Log

https://gist.github.com/dockillborn/094c023af4d9be8b66c27c4489889bea

### Latest.Log

https://gist.github.com/dockillborn/157dd6d3b317e8ee2c08e4345ccd20b1

**Comment by alekthefirst** [comment] 2024-12-17 02:52
This is a intermittent problem that can happen when placing mekanism blocks. If you would so kindly, i would like to know what block mekanism block was being placed at the moment of the crash and what the neighboring blocks are

**Comment by alekthefirst** [comment] 2024-12-22 23:20
For now, closing as duplicate of https://github.com/AllTheMods/ATM-10/issues/1051
This issue should now be fixed on Mekanisms end, but they haven't released that yet

**Closed by alekthefirst** 2024-12-22 23:20 UTC
Labels: Duplicate, Crash, Reported to Mod Dev
