### ISSUE TITLE
[Bug]: Some MMR structures don't see the hatches

### ISSUE THREAD

**Issue by shade1822226911** [AllTheMods/ATM-10#1463] opened 2024-12-19 10:44 UTC
### Possible Fixes

Yes

### Modpack Version

2.6

### What happened?

Since 2.6, the Automatic Hephaestus Forge doesn't work because it can't find any fluid hatches despite working in the last version, and it seems that even the Crucibles failed according to some.

**Comment by shade1822226911** [comment] 2024-12-21 15:26
2.8 fixed the Crucible, but the Auto Hephaestus Forge now doesn't see the item input buses, despite me breaking and replacing all of the hatches to check if it works.

I've noticed it only says "Missing input item!" when it contains fluids, and it says "No matching recipes found" when empty, and "Missing input item **bus**" when there are no buses in the multiblock.

**Comment by alekthefirst** [comment] 2024-12-22 17:08
Fixed in dev on MMRs end, see https://github.com/alec016/modular-machinery-reborn/issues/21

**Comment by alekthefirst** [comment] 2024-12-22 23:15
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1418
Closing this one to collect further hatch issues in one thread

**Closed by alekthefirst** 2024-12-22 23:15 UTC
Labels: Bug, Duplicate, Reported to Mod Dev, Mod Bug
