### ISSUE TITLE
[Bug]: Quest Book Empty after updating server

### ISSUE THREAD

**Issue by Dinodudeishgamer** [AllTheMods/ATM-10#1520] opened 2024-12-23 19:00 UTC
### Possible Fixes

Yes

### Modpack Version

2.9

### What happened?

After updating my hosted ATM10 server I can join and play on the server fine on the new update but the entire quest book is empty.

**Comment by alekthefirst** [comment] 2024-12-23 19:06
Likely missing a lot of files on the server
Some of our recent server packs has had permission issues on linux / unix systems, if you have console access, simply set proper permissions on all files, command can be found in https://github.com/AllTheMods/ATM-10/issues/1489 (which this issue is a duplicate of)
If you have no console access, unpack the server zip in your local computer before uploading to server

**Closed by alekthefirst** 2024-12-23 19:06 UTC
Labels: Bug
