### ISSUE TITLE
[CRASH] I can no longer join in my server and a normal world after a crash happended.

### ISSUE THREAD

**Issue by Svendly** [AllTheMods/ATM-10#246] opened 2024-08-12 10:21 UTC
### Possible Fixes

Yes

### Modpack Version

0.30

### What happened?

I put a blook in a purifier and an enchanted book, then my server crash. Also tried to replicated in a test world and happend the same now its impossible to join in both worlds.

### Crash Log

https://gist.github.com/Svendly/30939fff78218501df25ab6e767cc760

### Latest.Log

The game crashed whilst unexpected error Error: java.lang.IllegalStateException: Cannot get config value before config is loaded.

**Comment by alekthefirst** [comment] 2024-12-22 17:56
Duplicate of https://github.com/AllTheMods/ATM-10/issues/246
(i am aware this one came before, but it got resolved in the other one)

**Closed by alekthefirst** 2024-12-22 17:56 UTC
Labels: Duplicate, Crash
