### ISSUE TITLE
[Bug]: AdvancedAE Incorrect Recipes in JEI

### ISSUE THREAD

**Issue by HeroWillHD** [AllTheMods/ATM-10#1388] opened 2024-12-13 05:29 UTC
### Possible Fixes

Yes

### Modpack Version

2.3

### What happened?

I've checked other issues for duplicates, but couldn't find any reports of these specific incorrect recipes:

The recipe for "**Quantum Infusion**" liquid shows in JEI as:
_1000mb of Water_
1 Quantum Infused Dust
When it actually is:
_4000mb of Water_
1 Quantum Infused Dust

The recipe for "**Shattered Singularity**" item shows in JEI as:
_1000mb of Lava_
1 Singularity
2 Ender Dust
2 Sky Stone Dust
When it actually is:
_100mb of Lava_
1 Singularity
2 Ender Dust
2 Sky Stone Dust

I did read something about recipes in #954 but I don't know if it's related, feel free to delete/lock this issue if you feel it's a duplicate.

**Comment by alekthefirst** [comment] 2024-12-13 12:19
Currently we don't have a fix planned, AAE dev says its a JEI bug
https://i.imgur.com/VYdW4mg.png

**Comment by alekthefirst** [comment] 2024-12-22 21:17
Duplicate of https://github.com/AllTheMods/ATM-10/issues/954

**Closed by alekthefirst** 2024-12-22 21:17 UTC
Labels: Bug
