### ISSUE TITLE
[Bug]: Hostile Neural Networks Data Models not leveling up

### ISSUE THREAD

**Issue by shelman09** [AllTheMods/ATM-10#1395] opened 2024-12-13 14:40 UTC
### Possible Fixes

Yes

### Modpack Version

2.3

### What happened?

I have a blaze data model. I've killed about 60 blazes with it in the deep leaner. tried having the deep learner in my off hand as well as in the cruio slot for it with the same result. when you've killed enough that it should go up to the next stage it resets back to faulty.

**Comment by alekthefirst** [comment] 2024-12-22 23:49
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1034

**Closed by alekthefirst** 2024-12-22 23:49 UTC
Labels: Bug, Duplicate, Mod Bug
