### ISSUE TITLE
[Crash]: Brass Barbed Band causes client to crash.

### ISSUE THREAD

**Issue by QuaB-dev** [AllTheMods/ATM-10#1557] opened 2024-12-26 20:43 UTC
### Possible Fixes

No

### Modpack Version

2.11

### What happened?

We have a server and after the update to 2.11 my friends client just crashed when he logged in but mine not. When I go near him than my client crashes too.

We did some try and error and traced it to be the "Brass Barbed Band".
![image (2)](https://github.com/user-attachments/assets/7ae3c1b5-f18f-4b6a-b524-84f2555d8203)

### Crash Log

https://gist.github.com/QuaB-dev/8a0f799187eb86faf9e5a7d8f9061adf

### Latest.Log

https://gist.github.com/QuaB-dev/6c401ad0ddaebe4af0252391b7cb5f98

**Comment by alekthefirst** [comment] 2024-12-26 20:48
Known bug in iron's jewelry, recommend downgrading to atm10 2.10 for now (alternative solution in other thread)
This is a duplicate of https://github.com/AllTheMods/ATM-10/issues/1540

**Comment by TheBedrockMaster** [comment] 2024-12-26 21:44
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1540

**Closed by TheBedrockMaster** 2024-12-26 21:44 UTC
Labels: Duplicate, Crash
