### ISSUE TITLE
[Bug]: Dupe Glitch

### ISSUE THREAD

**Issue by XxArxAngelxX** [AllTheMods/ATM-10#992] opened 2024-10-31 02:21 UTC
### Possible Fixes

Yes

### Modpack Version

1.13

### What happened?

When using a tool for crafting, in my case an Iron Ore Hammer to make gold dust, if I'm in my inventory and press Tab, it moves the recipe to my inventory crafting. If I hit tab again, it adds another hammer into my inventory and keeps one in the craft menu. 

### latest.log

https://gist.github.com/XxArxAngelxX/6903823058d24492d795884594d9b6d7

**Comment by KenZync** [comment] 2024-11-04 08:05
confirmed

**Comment by alekthefirst** [comment] 2024-12-22 15:35
Duplicate of https://github.com/AllTheMods/ATM-10/issues/138
Please continue further discussion there

**Closed by alekthefirst** 2024-12-22 15:35 UTC
Labels: Bug, Duplicate, Reported to Mod Dev
