### ISSUE TITLE
[Bug]: Rubber from Productive Trees not attainable

### ISSUE THREAD

**Issue by dave36464736** [AllTheMods/ATM-10#1522] opened 2024-12-23 21:31 UTC
### Possible Fixes

Yes

### Modpack Version

2.10

### What happened?

When trying to craft Mystical Agriculture Rubber Seeds, You need Rubber from the productive trees mod. Which at this time, Has no recipe for attaining it and the dry rubber from Industrial Forgoing is not compatible. Fairly certain there is a tree tapper add on mod that adds this functionality. Or add the tags that allow dry rubber to also craft the rubber seeds.

**Comment by TheBedrockMaster** [comment] 2024-12-26 11:26
Dupe of https://github.com/AllTheMods/ATM-10/issues/1155

**Closed by TheBedrockMaster** 2024-12-26 11:26 UTC
Labels: Bug, Duplicate
