### ISSUE TITLE
[Crash]: Breaking a modular rougher.

### ISSUE THREAD

**Issue by NJM1564** [AllTheMods/ATM-10#1232] opened 2024-11-22 11:16 UTC
### Possible Fixes
Edit: Fixed by updating Modern Industrial Routers. Don't know about the curse log error though.

Yes

### Modpack Version

10-1.22

### What happened?

Broke a modular rougher.
[crash-2024-11-22_06.00.07-client.txt](https://github.com/user-attachments/files/17869174/crash-2024-11-22_06.00.07-client.txt)
[crash-2024-11-22_06.07.50-client.txt](https://github.com/user-attachments/files/17869175/crash-2024-11-22_06.07.50-client.txt)

In addition trying to submit this report through curse launcher's 
responded with a red boxed pop up with warning sign reading. "Failed to submit Minecraft crash log for 3695e71-fbbs-459c-b8f4-1d5306ec99.
![Screenshot (12742)](https://github.com/user-attachments/assets/be383571-3b18-410d-8783-3f64face8ce4)

### Crash Log

https://gist.github.com/NJM1564/404002836007410b29b7ca8b9bb40195

### Latest.Log

https://gist.github.com/NJM1564/0b3959eb112a5aca213a3104d411b252

**Comment by alekthefirst** [comment] 2024-12-23 13:38
Crash was caused by user added mod, and resolved by the user

**Closed by alekthefirst** 2024-12-23 13:38 UTC
Labels: Crash, Mod Bug
