### ISSUE TITLE
[Crash]: Random Crash after a few minutes of play

### ISSUE THREAD

**Issue by MooMcMooman** [AllTheMods/ATM-10#1567] opened 2024-12-27 06:18 UTC
### Possible Fixes

Yes

### Modpack Version

2.12

### What happened?

After a few minutes, minecraft just crashes, but it saves the world first, then dies. 

(I did some research, and it looks like it's a bug with sodium, cause I disabled it, and mc doesn't crash)

### Crash Log

https://gist.github.com/MooMcMooman/c84f4b9c910bf48ef30271df077496aa

### Latest.Log

https://gist.github.com/MooMcMooman/6b8075c2d0cea71e6935fb8bcbb4e3c7

**Comment by alekthefirst** [comment] 2024-12-27 17:43
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1547

**Comment by TheBedrockMaster** [comment] 2024-12-27 22:58
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1547

**Closed by TheBedrockMaster** 2024-12-27 22:58 UTC
Labels: Duplicate, Crash
