### ISSUE TITLE
[Bug]: Stick crafting

### ISSUE THREAD

**Issue by TheEmpireSro** [AllTheMods/ATM-10#23] opened 2024-06-28 05:02 UTC
### Possible Fixes

Yes

### Modpack Version

0.3

### What happened?

Well, I tried crafting a stick and it wants to give me pressure plates...
![2024-06-28_07 01 48](https://github.com/AllTheMods/ATM-10/assets/145923835/b1877b36-e129-49b7-be0e-25340ef9f830)

**Comment by Kevin-Marsh** [comment] 2024-06-29 21:40
This is an issue cause by the version of Polymorph. Updating manually will fix it for now but otherwise it will be fixed in next version.
[Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph/files/5480541)

**Closed by Kevin-Marsh** 2024-06-29 21:40 UTC
Labels: Bug, Duplicate, Reported to Mod Dev, Mod Bug

**Comment by TheBedrockMaster** [comment] 2025-01-03 01:47
Duplicate of https://github.com/AllTheMods/ATM-10/issues/21
