### ISSUE TITLE
[Bug]: Mystical Agriculture Seeds not craftable

### ISSUE THREAD

**Issue by Lucian0301** [AllTheMods/ATM-10#694] opened 2024-10-05 07:50 UTC
### Possible Fixes

Yes

### Modpack Version

10-0.62

### What happened?

Crafting Mystical Agriculture Steel seed and Silicon seed require Steel from Modular Force Field System and Silicon from EnderIO witch both have no recipe. Tried to use Steel from Mekanism and Silicon from AE2 and the seeds wont craft with that resources.

**Comment by TheBedrockMaster** [comment] 2024-10-05 08:47
Dupe of multiple other issues. We know.

**Closed by TheBedrockMaster** 2024-10-05 08:47 UTC
Labels: Bug
