### ISSUE TITLE
[Bug]: 2.7 broken recipes and ae crafting and more

### ISSUE THREAD

**Issue by theoriginalspre** [AllTheMods/ATM-10#1502] opened 2024-12-22 07:45 UTC
### Possible Fixes

Yes

### Modpack Version

2.7

### What happened?

I'm not wasting several posts so it's all goin here to make it easier.

Infinity ham marked as non edible now.

Quantum infusion fluid, suppose to be  1 infused dust and 1 bucket of water in jei. However it takes 4 buckets of water.

When autocratic singularities in the reaction chamber, jei shows 1 bucket of lava but the chamber only uses .1 buckets of lava

Autocrafting of any recipe that has more the. 15 ingredients or thousands of ingredients stalls out and has to be canceled and re done.

Non of these bugs were in 2.6 or 2.7

**Comment by alekthefirst** [comment] 2024-12-22 11:24
All of these bugs have been present for some time.

The infinity ham received some updates, some changes, and have already received even more that hasn't made it into ATM10 yet. The Ham features a lot on the recent commits page of Relics mod https://github.com/Octo-Studios/relics/commits/1.21.0/ . If issues with it persists after the next update please make a new issue about it then. 

The reaction chamber recipes are bugged with JEI, this was fixed in 2.7 but the AAE version got rolled back in 2.8 to unfix it, because of an AE2 crash. The fix will be back in a future update. Also a duplicate of https://github.com/AllTheMods/ATM-10/issues/1170

**Comment by alekthefirst** [comment] 2024-12-22 11:27
The auto crafting stalling has been a thing for a long time and can commonly be caused by NBT, lack of output return storage space, or lack of necessary energy storage reasons, and sometimes for no reason at all, and is not something we can currently resolve.

**Closed** 2024-12-22 11:38 UTC
Labels: Bug, Duplicate
