### ISSUE TITLE
[Bug]: Wrong information in crafting recipes for reaction chamber

### ISSUE THREAD

**Issue by Marviiiiiin** [AllTheMods/ATM-10#1170] opened 2024-11-16 22:44 UTC
### Possible Fixes

Yes

### Modpack Version

1.20

### What happened?

To craft "Quantum Infusion" Fluid you only needs 4B (4000 MB) of Water instead of 5 inside of the Reaction Chamber.
Same goes with "Shattered Singularity" it only need 0.1B (100MB) of Lava and not 1000MB as shown in the recipe.

Not something huge but I thought I share it here.

**Comment by solareon** [comment] 2024-11-18 09:58
It appears that the Entro Crystal and Entro Infused Ingot recipes in the reaction chamber are also the same way. Recipes calls for 1000mB of water but only 500mB is used

**Comment by alekthefirst** [comment] 2024-12-22 17:00
The reaction chamber recipes are bugged with JEI, this was fixed in 2.7 but the AAE version got rolled back in 2.8 to unfix it, because of an AE2 crash. The fix will be back in a future update.

**Comment by alekthefirst** [comment] 2024-12-22 21:17
Duplicate of https://github.com/AllTheMods/ATM-10/issues/954

**Closed by alekthefirst** 2024-12-22 21:17 UTC
Labels: Bug, Reported to Mod Dev
