### ISSUE TITLE
[Bug]: corrupted chunk/world with blood purifier

### ISSUE THREAD

**Issue by 2Scriptive** [AllTheMods/ATM-10#286] opened 2024-08-18 22:08 UTC
### Possible Fixes

Yes

### Modpack Version

.32 and .30

### What happened?

while using the blood purifier from evilcraft to disenchant amor/books, randomly, the game will freeze and come back with a message saying "server closed."  After receiving this message the server will reboot, but when someone tries to load in that has the chunk where the blood purifier is loaded, the server will crash again. People who do not have the chunk loaded in are able to join and roam freely unless they get to close and load the chunk in, then they will no longer be able to join the server or it will crash. I have recreated this on 3 separate occasions, ruining 3 worlds. 1st time, i was disenchanting a refined obsidian chestplate trying to remove the life mending enchantment. 2nd time was disenchanting a vengeance pickaxe, 3rd was with an enchanted book trying to remove a curse as well. These we're all done on 3rd party paid for hosted servers (dont know if that has anything to do with it). 

To fix the bug we had to reset the whole server (losing all progress and starting fresh). we tried updating to the newest version of the modpack at the time which was .32 and it did not fix.

### Developer reports

not sure how to get this, the mod is Evilcraft

**Comment by alekthefirst** [comment] 2024-12-22 17:59
Duplicate of https://github.com/AllTheMods/ATM-10/issues/277

**Closed by alekthefirst** 2024-12-22 17:59 UTC
Labels: Bug, Duplicate, Crash
