### ISSUE TITLE
[Crash]: Crash while crafting 2x2 framed drawer from functional storage

### ISSUE THREAD

**Issue by ThumperLP** [AllTheMods/ATM-10#516] opened 2024-09-16 06:17 UTC
### Possible Fixes

No

### Modpack Version

0.49 and 0.52

### What happened?

I have recently come across a disconnect/crash issue in 0.49 while attempting to craft a 2x2 framed drawer from Functional Storage.
Crafting recipe 1x 2x2 drawer 2x iron nuggets.

Clients 0.49 and 0.52 w/ 10gb ram
Server 0.49 w/ 10gb ram

if attempting to craft via Applied Energetics ME Crafting terminal the player will be disconnected from the server and have to pick up and replace the terminal in order to access the system once more.
[disconnect-2024-09-16_00.03.35-client.txt](https://github.com/user-attachments/files/17009107/disconnect-2024-09-16_00.03.35-client.txt)

upon attempting to craft the same item in a vanilla crafting table the server its self shuts down
[crash-2024-09-15_00.35.47-server.txt](https://github.com/user-attachments/files/17009115/crash-2024-09-15_00.35.47-server.txt)

I have verified this is also present in the 0.52 client but have not verified for server

also including 0.49 server logs

[JadeErrorOutput.txt](https://github.com/user-attachments/files/17009129/JadeErrorOutput.txt)
[debug.log](https://github.com/user-attachments/files/17009130/debug.log)
[latest.log](https://github.com/user-attachments/files/17009131/latest.log)

I can be reached best via discord for more information (ThumperLP in the ATM server)

### Crash Log

https://gist.github.com/ThumperLP/6153a241f13bfcd446e34abb99286835

### Latest.Log

https://gist.github.com/ThumperLP/0ddc94c104c2233e4e49acd1036d4313

**Comment by indikat0r** [comment] 2024-10-03 18:59
same here

**Comment by alekthefirst** [comment] 2024-12-22 17:19
Duplicate of https://github.com/AllTheMods/ATM-10/issues/171
Fixed in Functional Storage 1.3.4 released with ATM10 1.11

**Closed by alekthefirst** 2024-12-22 17:19 UTC
Labels: Duplicate, Crash, Reported to Mod Dev
