### ISSUE TITLE
[Crash]: DecoderException when joining server

### ISSUE THREAD

**Issue by ERMtn** [AllTheMods/ATM-10#1541] opened 2024-12-26 11:18 UTC
### Possible Fixes

Yes

### Modpack Version

2.11

### What happened?

The server starts fine, but while joining, right after the Loading terrain message, it instantly shows an exception:
_Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:custom_payload'_.

So right now the server is not accessible.

Looking through the server logs it shows the player joining, then some errors and then the disconnection.
<details>
  <summary>List of errors</summary>
  [26Dec2024 11:56:28.453] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.453] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.453] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.454] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.454] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.454] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.454] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.454] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.454] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.455] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.455] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.455] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.455] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.455] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.455] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.455] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.455] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.468] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.468] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.468] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.468] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:smooth_smooth_stone_column"}]'
  [26Dec2024 11:56:28.481] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:tiny_brick_bordered_deepslate"}]'
  [26Dec2024 11:56:28.482] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:tiny_brick_bordered_deepslate"}]'
  [26Dec2024 11:56:28.482] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:tiny_brick_bordered_deepslate"}]'
  [26Dec2024 11:56:28.482] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:tiny_brick_bordered_deepslate"}]'
  [26Dec2024 11:56:28.485] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:tiny_brick_bordered_deepslate"}]'
  [26Dec2024 11:56:28.485] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chipped:tiny_brick_bordered_deepslate"}]'
  [26Dec2024 11:56:28.574] [Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Name:"chisel:noborder/glass"}]'
</details>

The gist have 2 files, the disconnection log from /debug and the latest from /logs.

### Crash Log

https://gist.github.com/ERMtn/3add1c2ad32623a8fff26e7480404e04

### Latest.Log

https://gist.github.com/ERMtn/3add1c2ad32623a8fff26e7480404e04

**Comment by Flowelfox** [comment] 2024-12-26 12:13
Same here: https://github.com/AllTheMods/ATM-10/issues/1540

**Comment by TheBedrockMaster** [comment] 2024-12-26 12:16
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1540

**Closed by TheBedrockMaster** 2024-12-26 12:16 UTC
Labels: Duplicate, Crash
