### ISSUE TITLE
[Crash]: Rendering entity in world

### ISSUE THREAD

**Issue by RealCrashninja** [AllTheMods/ATM-10#280] opened 2024-08-18 05:34 UTC
### Possible Fixes

I believe so, I cant figure it out though

### Modpack Version

0.34

### What happened?

I was exploring around  looting structures as i normally do (as I am a loot hoarder)  I was around a spruce village when I suddenly crash I notice it is an error i recieve a lot besides an entity tick issue it seems to fail to render a certain entity (i see this this issue a lot on newer minecraft verions un like older version like 1.12.2 i see a ticking entity crash) i did mess with my video settings to help prevent my motherboard from starting on on fire, but as far as i'm aware its a rendering problem

### Crash Log

https://gist.github.com/RealCrashninja/38d68ccff33971ad4a159fb5d38e56b2

### Latest.Log

https://gist.github.com/RealCrashninja/ccc288488a7fc9f8ccdc02fa6d8fcfb3

**Comment by prinsmastertje** [comment] 2024-08-18 10:44
I have the same crash issue,

not on a server but in single player.

What happend?
i was trying to capture some mobs into a creature capture from just dire and in a outpost with a boss it crashed on me throwing the creature capure on the boss entity

[crash-2024-08-18_12.38.57-client.txt](https://github.com/user-attachments/files/16648080/crash-2024-08-18_12.38.57-client.txt)

**Comment by neilwightman** [comment] 2024-08-18 11:10
Seems to be related to https://github.com/iron431/irons-spells-n-spellbooks/issues/536

**Comment by Tricksz74** [comment] 2024-08-21 14:12
It also happen on 0.36 i'm playing on a server and my game crash immediately after joining

[crash-2024-08-21_15.43.41-client.txt](https://github.com/user-attachments/files/16692855/crash-2024-08-21_15.43.41-client.txt)

**Comment by alekthefirst** [comment] 2024-12-22 14:24
Duplicate of https://github.com/AllTheMods/ATM-10/issues/256
Fixed in Irons 3.4.5 released with ATM10 0.39

**Closed by alekthefirst** 2024-12-22 14:24 UTC
Labels: Duplicate, Crash
