### ISSUE TITLE
[Crash]: Some wandering trade item is crashing the client

### ISSUE THREAD

**Issue by Lucas-Dreveck** [AllTheMods/ATM-10#1551] opened 2024-12-26 17:33 UTC
### Possible Fixes

Yes

### Modpack Version

2.11

### What happened?

While trying to get the edelwood sapling from the wandering traders using an apotheosis spawner, I tried to get a few more, and noticed that when I clicked on one of the wandering traders that spawned, I instantly crashed, but only on the client side, I will leave the disconnect log

### Crash Log

https://gist.github.com/Lucas-Dreveck/d97e09040ef6a6a74a73e3dac581bfe4

**Comment by alekthefirst** [comment] 2024-12-26 18:03
Known bug in iron's jewlery, recommend downgrading to atm10 2.10 for now 
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1540

**Comment by TheBedrockMaster** [comment] 2024-12-26 21:43
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1540

**Closed by TheBedrockMaster** 2024-12-26 21:43 UTC
Labels: Duplicate, Crash
