### ISSUE TITLE
[Crash]: When my friend joins the server, the server crashes

### ISSUE THREAD

**Issue by FranktheFarmer162** [AllTheMods/ATM-10#1534] opened 2024-12-25 12:42 UTC
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-2.9

### What happened?

Hello,
when my friend joins the server it crashes. I contacted the gportal support and they said a block from productive bees is corrupted. I tried to remove that block but as soon as I got closer that block or whatever it is, the server crashed immediatly. Now I also cannot join that server. gportal said i should contact you if their solution will not work.

### Crash Log

https://gist.github.com/FranktheFarmer162/1f1f9e865cdb2373295eb559d755d3ce

**Comment by alekthefirst** [comment] 2024-12-25 13:12
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1513

**Closed** 2024-12-25 17:40 UTC
Labels: Duplicate, Crash, Reported to Mod Dev, Mod Bug
