### ISSUE TITLE
[Bug]: Accessing AE2 panel causes player to be disconnected

### ISSUE THREAD

**Issue by localzuk** [AllTheMods/ATM-10#1546] opened 2024-12-26 13:48 UTC
### Possible Fixes

Yes

### Modpack Version

2.11

### What happened?

Opening any AE2 panel on a powered system causes the player to be disconnected from the server. With the error "Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:custom_payload'.

I have also found the same error happens when I try and access the ME Drive that contains some disks. I suspect, looking at the log, this is a clash with something to do with Iron's Jewellery?

Accessing my other drives seems to not cause a disconnect, so it looks like its something stored in one or more of the disks in that drive. Accessing other devices works OK. Disconnecting the drives allows the AE2 panel to operate as well.

Attached the disconnect logs for a) opening an AE2 panel and b) trying to access an ME Extended Drive rather than latest.log, as that's more relevant.

### latest.log

https://gist.github.com/localzuk/eea80544639b92404f299d01f88f11b1

**Comment by alekthefirst** [comment] 2024-12-26 13:53
Known bug in iron's jewlery, recommend downgrading to atm10 2.10 for now (alternative solution in other thread)
This is a duplicate of https://github.com/AllTheMods/ATM-10/issues/1540 (where the other solution can also be found)

**Closed by alekthefirst** 2024-12-26 13:53 UTC
Labels: Duplicate, Crash

**Comment by localzuk** [comment] 2024-12-26 13:57
The alternative does not work in relation to this report - I do not have any Iron's Jewellery in my inventory - it is in the AE2 system, so it can't be removed like suggested. Will downgrade for now.
