### ISSUE TITLE
[Crash]: just dire things and ars enchanting apparatus

### ISSUE THREAD

**Issue by captainsedai** [AllTheMods/ATM-10#640] opened 2024-09-30 00:34 UTC
### Possible Fixes

Yes

### Modpack Version

atm 10 0.60

### What happened?

so i had the enchanting apparatus set up surrounded by hoppers pointing into pedestals with the arcane core the enchanting apparatus set up in the middle of them all. so i could automate the all the modium and unobtainium block. i had set down the just dire things clicker and had renedered the visual area so i could see where i was having it place to do what it does. when the render of the visual area hit the enchanting apparatus the game crashed. i can no longer load up my save. i have no idea how to fix this i sure hope you know how to

### Crash Log

https://gist.github.com/captainsedai/3558260ad9a54d26aa5c7a2a7f1a9ea2

### Latest.Log

https://gist.github.com/captainsedai/367be77e8db232592c4234984b5892c7

**Comment by alekthefirst** [comment] 2024-12-23 01:04
While i am unable to figure out which version this was fixed in, am i unable to reproduce this on ATM10 2.8

**Closed by alekthefirst** 2024-12-23 01:04 UTC
Labels: Crash, Mod Bug
