### ISSUE TITLE
[Bug]: Data Model downgrading inside Deep Learner when upgrading Artifacts

### ISSUE THREAD

**Issue by InspiringMilk** [AllTheMods/ATM-10#1139] opened 2024-11-13 19:33 UTC
### Possible Fixes

Yes

### Modpack Version

ATM10 1.19

### What happened?

https://github.com/user-attachments/assets/0259cb30-f817-4503-a6bf-243ccdd60b87
As per the title. I've had this issue before and could not trace down the source. Seems like the only thing that could cause this issue.

### latest.log

https://gist.github.com/InspiringMilk/c9211aa89dd60934418db7058bd0f324

**Comment by alekthefirst** [comment] 2024-12-22 23:48
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1139

**Closed by alekthefirst** 2024-12-22 23:48 UTC
Labels: Bug, Duplicate, Mod Bug
