### ISSUE TITLE
[Bug]: creative search crashes game

### ISSUE THREAD

**Issue by njasak** [AllTheMods/ATM-10#700] opened 2024-10-05 21:37 UTC
### Possible Fixes

Yes

### Modpack Version

0.62

### What happened?

When I go to creative mode and search for an item, I start to type it in and it crashes the game.

**Comment by njasak** [comment] 2024-10-05 21:37
[crash-2024-10-05_17.34.50-client.txt](https://github.com/user-attachments/files/17267506/crash-2024-10-05_17.34.50-client.txt)

**Comment by njasak** [comment] 2024-10-05 21:41
[crash-2024-10-05_17.34.50-client.txt](https://github.com/user-attachments/files/17267517/crash-2024-10-05_17.34.50-client.txt)
can not change label to crash sorry

**Comment by Erelaszun** [comment] 2024-10-05 22:40
I found my own temp fix for this issue:

Remove the following files:

All The Mods 10 - ATM10/kubejs/server_scripts/mods/ExtendedAE/InfinityCellRecipes.js
All The Mods 10 - ATM10/kubejs/startup_scripts/ExtendedAE/InfinityCells.js

Creative search will work, but laggy. Temp fix until a response.

**Comment by TheBedrockMaster** [comment] 2024-10-05 23:33
Dupe: https://github.com/AllTheMods/ATM-10/issues/692

**Closed by TheBedrockMaster** 2024-10-05 23:33 UTC
Labels: Duplicate, Crash

**Comment by sludgepudge** [comment] 2024-10-07 01:51
Why did this get closed when it's not resolved?

**Comment by njasak** [comment] 2024-10-07 02:02
It got resovled with the update and he closed it because it was the same as an issue before mine 
.64 fixed it

**Comment by TheBedrockMaster** [comment] 2024-10-07 02:14
> Why did this get closed when it's not resolved?

It is resolved but I closed it when I did because it was a dupe, I linked the issue it was a dupe of and I added the duplicate label.

**Comment by sludgepudge** [comment] 2024-10-07 02:42
> It is resolved but I closed it when I did because it was a dupe, I linked the issue it was a dupe of and I added the duplicate label.

My mistake, I didn't see that another update had come out.
