### ISSUE TITLE
[Crash]: The game crashed whilst rendering entity in world Error: java.lang.IllegalStateException: Not building!

### ISSUE THREAD

**Issue by GitJeppy** [AllTheMods/ATM-10#325] opened 2024-08-24 02:40 UTC
### Possible Fixes

Yes

### Modpack Version

0.38

### What happened?

I opened the game, walked around for a bit, and then randomly crashed for apparently no reason. I'll attach the crashlog below.

### Crash Log

https://gist.github.com/GitJeppy/9583b31108f071219a69671461220e18

### Latest.Log

https://gist.github.com/GitJeppy/5a4bf24d2e4f80b78e96be69f7e2497e

**Comment by Satherov** [comment] 2024-08-24 11:10
This is a known Issue with Ironspellbooks. Rendering a certain Entity will crash your game. In the latest version of the pack, the spawning of said entity was disabled.

To fix the crash, go to `/config/neoforge-server.toml` and set `removeErroringEntities = true`. If that doesnt help log into your world and run `/kill @e[type=irons_spellbooks:priest]` before it crashes you.

**Comment by alekthefirst** [comment] 2024-12-22 14:26
Duplicate of https://github.com/AllTheMods/ATM-10/issues/256
Fixed in Irons 3.4.5 released with ATM10 0.39

**Closed by alekthefirst** 2024-12-22 14:26 UTC
Labels: Duplicate, Crash, Reported to Mod Dev, Mod Bug
