### ISSUE TITLE
[Crash]: Typing anything in creative menu crashes

### ISSUE THREAD

**Issue by ClockyVaudeville** [AllTheMods/ATM-10#1367] opened 2024-12-10 08:41 UTC
### Possible Fixes
Unknown

### Modpack Version

ATM 10-2.1, game version 1.21.1
### What happened?

Every time I try to type anything in the creative menu I get a crash with the same crash type. I tried to give more memory in case that was the issue but no dice.

### Crash Log

https://gist.github.com/ClockyVaudeville/587dedeffe9085e2d6c7f563ec29c928

### Latest.Log

https://gist.github.com/ClockyVaudeville/5427759f0221ff79d8d8734185f36bdc

**Comment by alekthefirst** [comment] 2024-12-11 10:12
What were you typing
If the string you were typing contained the character `y`, then try removing the findme keybinds, then try again

**Comment by ClockyVaudeville** [comment] 2024-12-14 04:09
It was anything I tried to type, lime the second I hit a letter with the search bar open. I think this crash was from my trying to type "build wand" (the minecolonies one) and it crashed the moment I opened the search bar.

**Comment by BDGameDev** [comment] 2024-12-15 21:38
im having the same issue... same version and everything.. if i try to type anything it crashes

**Comment by alekthefirst** [comment] 2024-12-23 13:55
Crash related to modular routers tooltip or keybind
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1246

**Closed by alekthefirst** 2024-12-23 13:55 UTC
Labels: Duplicate, Crash, Mod Bug
