### ISSUE TITLE
[Crash]: Server crashes when opening me terminal on 1.1

### ISSUE THREAD

**Issue by Fangzwusky** [AllTheMods/ATM-10#816] opened 2024-10-18 16:47 UTC
### Possible Fixes

Yes

### Modpack Version

1.1

### What happened?

Every few hours since updating too 1.1 server crashes. usually while exiting a inventory and trying too open AE2 network with wireless terminal. long timeout freeze, then crash. Or crash on reconnecting. 

No other changes made, updated from 0.60

### Crash Log

https://gist.github.com/Fangzwusky/6190a132312947957fb7c44276936ee9

### Latest.Log

https://gist.github.com/Fangzwusky/b4aa668b93a64de4a5f95166d0b32c9d

**Comment by alekthefirst** [comment] 2024-12-24 13:10
Fixed in crafting tweaks 21.1.3, released with ATM10 1.12
Duplicate of https://github.com/AllTheMods/ATM-10/issues/398

**Closed by alekthefirst** 2024-12-24 13:10 UTC
Labels: Crash, Reported to Mod Dev, Mod Bug
