### ISSUE TITLE
[Crash]: Crash when type y on AE system. 

### ISSUE THREAD

**Issue by alucard0215** [AllTheMods/ATM-10#572] opened 2024-09-22 00:48 UTC
### Possible Fixes

Yes

### Modpack Version

ATM 10 0.55

### What happened?

I was trying to see my mystical itens and twice when i type @mys my game stop n crash

### Crash Log

https://gist.github.com/alucard0215/b84e2607b0c69998d239dd43e7a9188d

### Latest.Log

https://gist.github.com/alucard0215/dc2d3c4096c59aed63982ef6905915e9

**Comment by SurfySurk** [comment] 2024-10-13 03:20
I recently had this error in version 0.64 of ATM10 and had determined the cause is the findme mod and disabling the keybind to "Search Nearby Inventories For Items" seems to have fixed this issue. Since I am on version 0.64 I can't speak about any later version.

**Comment by alekthefirst** [comment] 2024-12-23 13:27
Resolved in ATM10 2.9 by removing the FindMe mod
Duplicate of https://github.com/AllTheMods/ATM-10/issues/543

**Closed by alekthefirst** 2024-12-23 13:27 UTC
Labels: Crash, Mod Bug
