### ISSUE TITLE
Functional storage single drawr and cupboard from Hancrafted have a recpie conflict[Bug]: 

### ISSUE THREAD

**Issue by 1matto** [AllTheMods/ATM-10#104] opened 2024-07-15 12:31 UTC
### Possible Fixes

Yes

### Modpack Version

0.12

### What happened?

ther's a recipe conflict wit the single drawer and the cupboard in version 0.12 of ATM10

**Comment by aAndrew3030** [comment] 2024-07-15 21:09
Duplicate of 
https://github.com/AllTheMods/ATM-10/issues/98

**Comment by Kevin-Marsh** [comment] 2024-07-16 10:28
This will be patched in the next version.

**Closed by Kevin-Marsh** 2024-07-16 10:28 UTC

**Comment by TheBedrockMaster** [comment] 2025-01-07 08:28
Duplicate of
 https://github.com/AllTheMods/ATM-10/issues/98
